<?php
/** @var Webgriffe_OpenGraph_Block_Opengraph $this */
/** @var Mage_Catalog_Model_Category $category */
$category = Mage::registry('current_category');
?>
<?php if ((string)$this->getApplicationId() !== ''): ?>
    <meta property="fb:app_id" content="<?php echo (string)$this->getApplicationId(); ?>" />
<?php endif;?>
<?php if ((string)$this->getAdminId() !== ''): ?>
    <meta property="fb:admins" content="<?php echo (string)$this->getAdminId(); ?>" />
<?php endif;?>
<?php if ($category): ?>
    <meta property="og:url" content="<?php echo Mage::helper('core/url')->getCurrentUrl();?>" />
    <meta property="og:type" content="product.group" />
    <meta property="og:title" content="<?php echo $this->getOpenGraphHelper()->sanitizeString($category->getName()) ?>" />
    <meta property="og:description" content="<?php echo $this->getOpenGraphHelper()->sanitizeString($category->getDescription()) ?>" />
    <meta property="og:image" content="<?php echo $category->getImageUrl(); ?>" />
<?php endif; ?>
